package city

const ERROR_CITY = 0x40000

const ERROR_CITY_NOT_FOUND_PCITY = ERROR_CITY + 1

const ERROR_CITY_NOT_FOUND_ID = ERROR_CITY + 2

const ERROR_CITY_NOT_FOUND = ERROR_CITY + 3

const ERROR_CITY_NOT_FOUND_ALIAS = ERROR_CITY + 4
